package beattobeatonline;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JButton;

public class Main extends javax.swing.JFrame {
    JButton [] btnMenuList;
    Color gray = new Color(50, 50, 50);

    public Main() {
        initComponents();
        
        //rounded frame
        setShape(new RoundRectangle2D.Double(0, 0, 1280, 720, 20, 20));
        setSize(1280, 720);
        setLocationRelativeTo(null);
        
        // tab
        pnlTabContent.setLayout(new CardLayout());
        pnlTabContent.add(new Home(), "home");
        pnlTabContent.add(new Search(), "search");
        pnlTabContent.add(new LikedTracks(), "likedtracks");
        pnlTabContent.add(new AboutUs(), "aboutus");
        pnlTabContent.add(new LogIn(), "login");
        
        btnMenuList = new JButton[] {btnHome, btnSearch, btnLikedTracks, btnAboutUs, btnLogIn};
        for(JButton btn : btnMenuList) {
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // mau chu
                    for(JButton btn : btnMenuList) {
                        btn.setForeground(gray);
                    }
                    JButton b = (JButton)e.getSource();
                    b.setForeground(Color.BLACK);
                    
                    // show tab
                    String name = e.getActionCommand().toLowerCase().replaceAll(" ", "");
                    CardLayout c = (CardLayout) pnlTabContent.getLayout();
                    c.show(pnlTabContent, name);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new beattobeatonline.componment.MyPanel();
        windowTitleBar = new beattobeatonline.componment.WindowTitleBar();
        pnlSidebar = new javax.swing.JPanel();
        btnHome = new beattobeatonline.componment.MyButton();
        btnSearch = new beattobeatonline.componment.MyButton();
        btnLikedTracks = new beattobeatonline.componment.MyButton();
        btnAboutUs = new beattobeatonline.componment.MyButton();
        btnLogIn = new beattobeatonline.componment.MyButton();
        pnlTabContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beat To Beat");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        windowTitleBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        windowTitleBar.setFrame(this);

        pnlSidebar.setBackground(new java.awt.Color(255, 255, 255));
        pnlSidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        btnHome.setBackground(null);
        btnHome.setBorder(null);
        btnHome.setForeground(new java.awt.Color(80, 80, 80));
        btnHome.setText("Home");
        btnHome.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSearch.setBackground(null);
        btnSearch.setBorder(null);
        btnSearch.setForeground(new java.awt.Color(80, 80, 80));
        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLikedTracks.setBackground(null);
        btnLikedTracks.setBorder(null);
        btnLikedTracks.setForeground(new java.awt.Color(80, 80, 80));
        btnLikedTracks.setText("Liked Tracks");
        btnLikedTracks.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnLikedTracks.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLikedTracks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAboutUs.setBackground(null);
        btnAboutUs.setBorder(null);
        btnAboutUs.setForeground(new java.awt.Color(80, 80, 80));
        btnAboutUs.setText("About Us");
        btnAboutUs.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLogIn.setBackground(null);
        btnLogIn.setBorder(null);
        btnLogIn.setForeground(new java.awt.Color(80, 80, 80));
        btnLogIn.setText("Log In");
        btnLogIn.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnLogIn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLikedTracks, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnLikedTracks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );

        pnlTabContent.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout pnlTabContentLayout = new javax.swing.GroupLayout(pnlTabContent);
        pnlTabContent.setLayout(pnlTabContentLayout);
        pnlTabContentLayout.setHorizontalGroup(
            pnlTabContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTabContentLayout.setVerticalGroup(
            pnlTabContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlTabContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(windowTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1278, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(windowTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnHome.doClick();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beattobeatonline.componment.MyButton btnAboutUs;
    private beattobeatonline.componment.MyButton btnHome;
    private beattobeatonline.componment.MyButton btnLikedTracks;
    private beattobeatonline.componment.MyButton btnLogIn;
    private beattobeatonline.componment.MyButton btnSearch;
    private beattobeatonline.componment.MyPanel pnlMain;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTabContent;
    private beattobeatonline.componment.WindowTitleBar windowTitleBar;
    // End of variables declaration//GEN-END:variables
}
