/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package beattobeatonline.componment;

import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class Sidebar extends javax.swing.JPanel {
    
    public Sidebar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnHonw = new beattobeatonline.componment.MyButton();
        btnSearch = new beattobeatonline.componment.MyButton();
        btnLikedTracks = new beattobeatonline.componment.MyButton();
        btnAboutUs = new beattobeatonline.componment.MyButton();
        btnLogIn = new beattobeatonline.componment.MyButton();

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        btnHonw.setBackground(null);
        btnHonw.setBorder(null);
        btnHonw.setForeground(new java.awt.Color(80, 80, 80));
        btnHonw.setText("Home");
        btnHonw.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnHonw.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHonw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSearch.setBackground(null);
        btnSearch.setBorder(null);
        btnSearch.setForeground(new java.awt.Color(80, 80, 80));
        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLikedTracks.setBackground(null);
        btnLikedTracks.setBorder(null);
        btnLikedTracks.setForeground(new java.awt.Color(80, 80, 80));
        btnLikedTracks.setText("Liked Tracks");
        btnLikedTracks.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnLikedTracks.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLikedTracks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAboutUs.setBackground(null);
        btnAboutUs.setBorder(null);
        btnAboutUs.setForeground(new java.awt.Color(80, 80, 80));
        btnAboutUs.setText("About Us");
        btnAboutUs.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnLogIn.setBackground(null);
        btnLogIn.setBorder(null);
        btnLogIn.setForeground(new java.awt.Color(80, 80, 80));
        btnLogIn.setText("Log In");
        btnLogIn.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        btnLogIn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLikedTracks, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHonw, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnHonw, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnLikedTracks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private beattobeatonline.componment.MyButton btnAboutUs;
    private beattobeatonline.componment.MyButton btnHonw;
    private beattobeatonline.componment.MyButton btnLikedTracks;
    private beattobeatonline.componment.MyButton btnLogIn;
    private beattobeatonline.componment.MyButton btnSearch;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
